### ISSUE TITLE
Add zoom in-zoom out controls on map

### ISSUE THREAD

**Issue by lars-raaum** [lars-raaum/kom-inn#50] opened 2017-01-04 20:56 UTC

**Comment by alkemann** [comment] 2017-01-05 16:57
Works correctly on localhost, is very likely to be related to #46 as center being offset and missing the right part of the map where the zoom buttons are seems very connected

**Comment by alkemann** [comment] 2017-01-05 17:22
This was caused by a bug that hid half the map. Fixed on prod. If it appears to not be fixed, you need a hard refresh.

**Closed as completed by alkemann** 2017-01-05 17:22 UTC
Labels: enhancement
