### ISSUE TITLE
Map not centering on guest when selecting guest

### ISSUE THREAD

**Issue by lars-raaum** [lars-raaum/kom-inn#46] opened 2017-01-04 19:59 UTC
It is off with a certain pattern. 

Produced in Chrome on Windows.

**Comment by alkemann** [comment] 2017-01-05 17:22
Caused by bug in CSS. Fixed now. If it appears to not be fixed, do a HARD refresh of the site ( cmb + shift+r on mac, ctr+f5 on win)

**Closed as completed** 2017-01-05 17:22 UTC
Labels: bug
